# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Build your React application
RUN npm run build

# Expose the port your React app will run on (usually 3000)
#EXPOSE 3000

# Define the command to start your app
#CMD ["npm", "start"]
